name: Documentation

on:
  release:
    types: [created]

jobs:
  build:
  
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r dev_requirements.txt
      - name: Build package
        run: |
          python setup.py build
      - name: Make doc
        run: |
          .\make.bat html
        working-directory: ./docs
        env:
          PYLIB_VERSION: ${{ github.event.release.tag_name }}             

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: docs
          # A file, directory or wildcard pattern that describes what to upload
          path: ./docs/_build/html

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html

